### ISSUE TITLE
[BUG] 表格在手机上显示会越界

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/yazicbs.github.io#29]
![image](https://github.com/user-attachments/assets/b76929fe-3f3d-4647-926e-3201e48ac511)

**Comment by DuckDuckStudio** [comment]
查看方式：百度搜索

**Comment by DuckDuckStudio** [comment]
可能的解决方式：
```css
@media screen and (max-width: 600px) {
    /* 在小屏幕上，使表格容器出现横向滚动条 */
    div.table-wrapper {
        overflow-x: auto;
    }
}
```
But, 本地测试失败。
